LS_ALIAS = {
    "file_name": "/.ls.rc",
    "content": """
# .ls.rc
# this file was generated by the pypi ofgrenudo package.
alias ls="ls -lh --color=auto"
alias ll="ls -lah --color=auto"
""",
    "signature": """
if [ -f ~/.ls.rc ]; then
    source ~/.ls.rc
fi
    """,
}

COMMANDS_ALIAS = {
    "file_name": "/.commands.rc",
    "content": """
# .commands.rc
# this file was generated by the pypi ofgrenudo package.
alias reboot="sudo reboot"
alias grep="grep --color=auto"
alias cp="cp -i" # confirms before overwriting something.
alias mv="mv -i" # confirms before overwriting something.
alias rm="rm -I --preserve-root" # confirms before deleting something.
alias free="free -h"
alias shasum="openssl dgst -sha256"
alias ports="nmap localhost"
alias lanip="uvx ofgrenudo lanip"
alias wanip="uvx ofgrenudo wanip"
""",
    "signature": """
if [ -f ~/.commands.rc ]; then
    source ~/.commands.rc
fi
    """,
}
